---
- hosts: concourse
  gather_facts: no
  become: yes
  tasks:
    # Ubuntu no longer comes with Python installed.  Fix this.
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: concourse
  become: yes
  roles:
    - docker

- hosts: web
  gather_facts: no
  roles:
    - concourse-service
    - web

- hosts: worker
  gather_facts: no
  roles:
    - concourse-service
    - worker
