- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check vagrant running
      shell: vagrant status | grep web | grep running

    - name: vagrant ssh-config
      command: vagrant ssh-config {{ item }}
      register: ssh_config
      with_items:
        - web
        - worker

    - name: add hosts
      add_host:
        hostname:         "{{ item['name'] }}"
        groups:           "{{ item['name'] }},needs_python"
        ansible_ssh_host: "{{ item.value.stdout_lines[1].split(' ') | last }}"
        ansible_user:     "{{ item.value.stdout_lines[2].split(' ') | last }}"
        ansible_port:     "{{ item.value.stdout_lines[3].split(' ') | last }}"
        ansible_ssh_private_key_file: "{{ item.value.stdout_lines[7].split(' ') | last }}"
      with_items:
        - name: web
          value: "{{ ssh_config['results'][0] }}"
        - name: worker
          value: "{{ ssh_config['results'][1] }}"
          
- hosts: needs_python
  gather_facts: no
  become: yes
  tasks:
    # Ubuntu no longer comes with Python installed.  Fix this.
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        
# Gather facts
- hosts: web
- hosts: worker

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # override with
    default_interface_name: 'ansible_enp0s8'
  tasks:
    # - debug: var=hostvars

    - name: Write inventory
      template:
        src:  vagrant-inventory.j2
        dest: ./inventory/vagrant
        backup: yes
