---
# A builder of dashboard PR code

resource_types:
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource

resources:
  - name: concourse-pr-test
    type: git-branch-heads
    source:
      uri: https://bitbucket.org/jkamenik-fourv/concourse-pr-test.git
      branches:
        - CRPI-*

jobs:
  - name: concourse-pr-test
    public: true
    plan:
      - get: concourse-pr-test
        trigger: true
        version: every
      - task: unit
        file: concourse-pr-test/ci/unit.yml
