- name: Download concourse
  get_url:
    url: "https://github.com/concourse/concourse/releases/download/v{{ concourse_binary_version }}/concourse_linux_amd64"
    dest: "{{ concourse_exec_path }}"
    mode: 0755

- name: Install keys
  copy:
    src: "./keys/{{ item }}"
    dest: "{{ concourse_keys_path }}"
    mode: 0600
  with_items:
    - "tsa_host_key.pub"
    - "worker_key"
  notify: restart concourse

- include: service.yml
