---
# TODO: Remove by including docker in the fourv repo
- name: Add docker key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: Add docker repo
  apt_repository:
    filename: docker
    repo: "deb https://apt.dockerproject.org/repo {{ docker_repo_version }} main"
    state: present
