---
# the file containing the defaults

default_interface: "{{ hostvars[inventory_hostname][default_interface_name] }}"
default_interface_ipv4: "{{ default_interface['ipv4']['address'] }}"

tsa_default_interface_ip: "{{ hostvars[tsa_hostname][default_interface_name]['ipv4']['address'] }}"

concourse_version: concourse/concourse
concourse_user: concourse
concourse_password: changeme
concourse_url: "http://{{ default_interface_ipv4 }}"
concourse_install_path: /usr/local/share/concourse
concourse_keys_path: "{{ concourse_install_path }}/keys"
concourse_log_path: /var/log/concourse

# We always want to get the newest root certs
docker_repo_version: "ubuntu-xenial"
docker_version: "1.12.3-0~xenial"
docker_compose_version: "1.8.0"
docker_compose_path: "/usr/local/bin/docker-compose"

loadbalancer_version: nginx:1.11.7-alpine
install_ssl: false

db_version: postgres:9.5
db_name: concourse
db_user: concourse
db_password: changeme
