---
# the file containing the defaults

concourse_version: concourse/concourse
concourse_user: concourse
concourse_password: changeme
concourse_url: "http://{{ ansible_default_ipv4['addres'] }}"
concourse_install_path: /usr/local/share/concourse
concourse_log_path: /var/log/concourse

# We always want to get the newest root certs
docker_repo_version: "ubuntu-xenial"
docker_version: "1.12.3-0~xenial"
docker_compose_version: "1.8.0"
docker_compose_path: "/usr/local/bin/docker-compose"

loadbalancer_version:

db_version: postgres:9.5
db_name: concourse
db_user: concourse
db_password: changeme
